#!/usr/bin/env python3
"""Generated-Trivyignore-Renderer (M6 Welle 4a; ADR 0044).

Rendert `deploy/security/vulnignore.yaml` (Audit-Source-of-Truth) zu
`deploy/security/.trivyignore` (Trivy-natives Plain-Text-Format).

Pattern-Verankerung: ADR 0044 §2.3 Render-Script-Vertrag. Schaerft
ADR 0043 §2.2-Defer-Form per ADR-0011-Pattern (additive Erweiterung):
generierte `.trivyignore` ist zulaessig, wenn aus strukturierter
YAML-Audit-Source-of-Truth mit Pflicht-Feldern `id`/`reason`/
`expires`/`scope` produziert.

Vertrag:
- Pflicht-Felder `id` + `reason` + `expires` + `scope` pro Eintrag.
- `expires` als ISO-8601-Datum (YYYY-MM-DD); abgelaufene Eintraege
  brechen den Lauf mit EXIT=1.
- Optionales Scope-Filter-Argument (z. B. `--scope otel-collector`);
  `scope: *` matcht jedes Filter.
- Output-Datei `.trivyignore` wird **nicht** versioniert
  (`.gitignore`-Eintrag); diese YAML-Datei ist die kanonische
  Quelle.
- Bei keinem Treffer im Scope-Filter wird die Output-Datei
  entfernt (kein leerer File-Drift).

Pattern-Praezedenz: `tools/check_noqa.py` (CLI-Struktur),
`tools/check_spdx.py` (Lint-Fail-Mode), m-trace-Schwester-Repo
(`scripts/render-trivyignore.sh`; Logik 1:1 in Python portiert mit
PyYAML-statt-awk-Parser).
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path
from typing import Any

import yaml

_HEADER_LINES = (
    "# Generated by tools/render_trivyignore.py from deploy/security/vulnignore.yaml",
    "# DO NOT EDIT this file directly - change vulnignore.yaml and re-run.",
    "# ADR 0044 (Generated-Trivyignore-Permit, M6 Welle 4a; ADR-0011-Schaerfung an ADR-0043 §2.2).",
)


def _scope_matches(entry_scope: str, scope_filter: str) -> bool:
    if not scope_filter:
        return True
    if not entry_scope:
        return False
    items = [token.strip() for token in entry_scope.split(",")]
    return any(item == "*" or item == scope_filter for item in items)


def _emit_entry(
    entry: dict[str, Any],
    *,
    today: dt.date,
    scope_filter: str,
) -> tuple[list[str], bool]:
    """Returns (rendered_lines, had_error)."""

    cve_id = str(entry.get("id") or "").strip()
    if not cve_id:
        print(
            "render-trivyignore: entry missing `id` field - abort.",
            file=sys.stderr,
        )
        return ([], True)

    expires_raw = entry.get("expires")
    if not expires_raw:
        print(
            f"render-trivyignore: {cve_id} has no `expires` field - abort.",
            file=sys.stderr,
        )
        return ([], True)

    expires_str = str(expires_raw)
    try:
        expires_date = dt.date.fromisoformat(expires_str)
    except ValueError:
        print(
            f"render-trivyignore: {cve_id} expires ({expires_str}) not ISO-8601 (YYYY-MM-DD) - abort.",
            file=sys.stderr,
        )
        return ([], True)

    if expires_date < today:
        print(
            f"render-trivyignore: {cve_id} expired ({expires_str}) - renew or remove the entry.",
            file=sys.stderr,
        )
        return ([], True)

    entry_scope = str(entry.get("scope") or "").strip()
    if not _scope_matches(entry_scope, scope_filter):
        return ([], False)

    reason = str(entry.get("reason") or "").strip()
    scope_display = entry_scope or "*"
    comment = f"# {cve_id} - {reason} (expires {expires_str}, scope {scope_display})"
    return ([comment, cve_id], False)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render deploy/security/vulnignore.yaml to .trivyignore (ADR 0044)."
    )
    parser.add_argument(
        "--source",
        default="deploy/security/vulnignore.yaml",
        help="Audit-Source-of-Truth YAML (default: deploy/security/vulnignore.yaml).",
    )
    parser.add_argument(
        "--target",
        default="deploy/security/.trivyignore",
        help="Output Trivy-Ignore-Datei (default: deploy/security/.trivyignore).",
    )
    parser.add_argument(
        "--scope",
        default="",
        help="Scope-Filter (z. B. otel-collector); leer = alle Scopes.",
    )
    parser.add_argument(
        "--today",
        default="",
        help="Override fuer heute (YYYY-MM-DD); fuer Tests.",
    )
    return parser


def _resolve_today(today_arg: str) -> dt.date | None:
    if not today_arg:
        return dt.datetime.now(tz=dt.UTC).date()
    try:
        return dt.date.fromisoformat(today_arg)
    except ValueError:
        print(
            f"render-trivyignore: --today ({today_arg}) not ISO-8601 - abort.",
            file=sys.stderr,
        )
        return None


def _render_entries(
    ignore_list: list[Any],
    *,
    today: dt.date,
    scope_filter: str,
) -> tuple[list[str], int, bool]:
    """Returns (rendered_lines_without_header, entry_count, had_error)."""

    body_lines: list[str] = []
    entry_count = 0
    had_error = False
    for entry in ignore_list:
        if not isinstance(entry, dict):
            print(
                f"render-trivyignore: entry is not a mapping ({entry!r}) - abort.",
                file=sys.stderr,
            )
            had_error = True
            continue
        lines, entry_error = _emit_entry(
            entry,
            today=today,
            scope_filter=scope_filter,
        )
        if entry_error:
            had_error = True
            continue
        if lines:
            body_lines.extend(lines)
            entry_count += 1
    return body_lines, entry_count, had_error


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    source_path = Path(args.source)
    target_path = Path(args.target)

    if not source_path.exists():
        print(f"render-trivyignore: {source_path} not found", file=sys.stderr)
        return 1

    today = _resolve_today(args.today)
    if today is None:
        return 1

    raw = yaml.safe_load(source_path.read_text(encoding="utf-8")) or {}
    trivy_block = raw.get("trivy") or {}
    ignore_list: list[Any] = trivy_block.get("ignore") or []

    body_lines, entry_count, had_error = _render_entries(
        ignore_list,
        today=today,
        scope_filter=args.scope,
    )
    if had_error:
        return 1

    # Output-Datei wird immer geschrieben (Header-only bei null Treffer);
    # `image-audit` mountet die Datei per `--ignorefile`, deshalb darf
    # sie nicht fehlen — Trivy akzeptiert eine Header-only-Datei
    # problemlos.
    output_lines = [*_HEADER_LINES, *body_lines]
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text("\n".join(output_lines) + "\n", encoding="utf-8")
    word = "entry" if entry_count == 1 else "entries"
    print(f"render-trivyignore: wrote {target_path} ({entry_count} {word})")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
